import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Activity, Bell, CreditCard, LayoutDashboard, Package, RefreshCw, Search, ShieldCheck, ShoppingBag, Store, UserRound } from 'lucide-react';
import { money } from '@/lib/money';
import type { Audit, Customer, Notification, Order, OrderEvent, Overview, Product, StudioTab, Supplier } from '@/types';
import { OperationalOrders, OperationalProducts, OperationalSuppliers } from './StudioOperationalTables';

async function request<T>(url:string):Promise<T>{const r=await fetch(url,{credentials:'include'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`Request failed (${r.status})`);return b as T;}
const nav:Array<{id:StudioTab;label:string;icon:typeof LayoutDashboard}>=[
 {id:'overview',label:'Overview',icon:LayoutDashboard},{id:'orders',label:'Orders',icon:ShoppingBag},{id:'payments',label:'Payments',icon:CreditCard},{id:'products',label:'Products',icon:Package},{id:'sourcing',label:'Sourcing',icon:Store},{id:'suppliers',label:'Suppliers',icon:Store},{id:'customers',label:'Customers',icon:UserRound},{id:'notifications',label:'Notifications',icon:Bell},{id:'audit',label:'Audit log',icon:Activity}
];
export default function ProductionStudioOps(){
 const [tab,setTab]=useState<StudioTab>('overview');const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [data,setData]=useState<{overview:Overview|null;orders:Order[];products:Product[];suppliers:Supplier[];notifications:Notification[]}>({overview:null,orders:[],products:[],suppliers:[],notifications:[]});
 const load=async()=>{setLoading(true);setError('');try{const [o,or,p,s,n]=await Promise.all([request<Overview>('/api/admin/overview'),request<{orders:Order[]}>('/api/admin/orders'),request<{products:Product[]}>('/api/admin/products'),request<{suppliers:Supplier[]}>('/api/admin/suppliers'),request<{notifications:Notification[]}>('/api/admin/notifications')]);setData({overview:o,orders:or.orders||[],products:p.products||[],suppliers:s.suppliers||[],notifications:n.notifications||[]});}catch(e){setError(e instanceof Error?e.message:'Studio could not load.')}finally{setLoading(false)}};
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(id)},[]);
 const orders=useMemo(()=>data.orders.filter(x=>`${x.order_number} ${x.delivery_name} ${x.product_name} ${x.buyer_email}`.toLowerCase().includes(q.toLowerCase())),[data.orders,q]);
 const products=useMemo(()=>data.products.filter(x=>`${x.name} ${x.brand} ${x.category} ${x.supplier_name}`.toLowerCase().includes(q.toLowerCase())),[data.products,q]);
 const suppliers=useMemo(()=>data.suppliers.filter(x=>`${x.name} ${x.location} ${x.phone}`.toLowerCase().includes(q.toLowerCase())),[data.suppliers,q]);
 const customers=useMemo(()=>data.overview?.customers?.filter(x=>`${x.name} ${x.email}`.toLowerCase().includes(q.toLowerCase()))||[],[data.overview?.customers,q]);
 return <main className="min-h-screen bg-[#080a12] text-white"><div className="mx-auto flex min-h-screen max-w-[1800px]">
  <aside className="sticky top-0 hidden h-screen w-64 shrink-0 flex-col border-r border-white/10 bg-[#0b0d17] p-4 lg:flex"><div className="flex items-center gap-3 px-2 py-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-vura-500 font-black">V</span><div><b>Vura Studio</b><div className="text-[11px] text-white/35">Commerce operating system</div></div></div><nav className="mt-6 flex-1 space-y-1">{nav.map(x=>{const I=x.icon;return <button key={x.id} onClick={()=>setTab(x.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${tab===x.id?'bg-vura-500 shadow-lg shadow-vura-500/20':'text-white/55 hover:bg-white/5 hover:text-white'}`}><I size={16}/>{x.label}</button>})}</nav><div className="border-t border-white/10 pt-3 text-xs text-white/35"><div className="flex items-center gap-2"><ShieldCheck size={14}/> Server-authorized workspace</div></div></aside>
  <section className="min-w-0 flex-1"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#080a12]/90 backdrop-blur-xl"><div className="flex h-[72px] items-center gap-3 px-5 md:px-8"><div className="relative max-w-2xl flex-1"><Search className="absolute left-3.5 top-3.5 text-white/30" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search orders, products, customers, suppliers…" className="w-full rounded-xl border border-white/10 bg-white/[.035] py-3 pl-10 pr-4 text-sm outline-none focus:border-vura-400"/></div><button onClick={()=>void load()} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10" aria-label="Refresh"><RefreshCw size={17} className={loading?'animate-spin':''}/></button></div><div className="flex gap-2 overflow-x-auto px-5 pb-3 lg:hidden">{nav.map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`shrink-0 rounded-lg px-3 py-2 text-xs font-bold ${tab===x.id?'bg-vura-500':'bg-white/5 text-white/55'}`}>{x.label}</button>)}</div></header>
  <div className="p-5 md:p-8">{error&&<div className="mb-5 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}{loading&&!data.overview?<Loading/>:<>
   {tab==='overview'&&<OverviewView o={data.overview} notifications={data.notifications} onTab={setTab}/>} {tab==='orders'&&<OperationalOrders orders={orders} suppliers={data.suppliers} onRefresh={load}/>} {tab==='payments'&&<Payments orders={data.orders}/>} {tab==='products'&&<OperationalProducts products={products} suppliers={data.suppliers} onRefresh={load}/>} {tab==='sourcing'&&<Sourcing orders={data.orders}/>} {tab==='suppliers'&&<OperationalSuppliers suppliers={suppliers} onRefresh={load}/>} {tab==='customers'&&<Customers customers={customers}/>} {tab==='notifications'&&<Notifications items={data.notifications}/>} {tab==='audit'&&<AuditView items={data.overview?.audit||[]} events={data.overview?.orderEvents||[]}/>} 
  </>}</div></section></div></main>;
}
function OverviewView({o,notifications,onTab}:{o:Overview|null;notifications:Notification[];onTab:(x:StudioTab)=>void}){if(!o)return <Empty text="No overview data."/>;return <><Header title="Overview" subtitle="Live commerce operations, revenue, sourcing and admin activity."/><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Stat label="Live products" value={String(o.liveProducts)}/><Stat label="Orders this month" value={String(o.monthlyOrders)}/><Stat label="Revenue this month" value={money(o.monthlyRevenueKobo)}/><Stat label="Profit this month" value={money(o.monthlyProfitKobo)}/></div><div className="mt-6 grid gap-5 xl:grid-cols-3"><Card className="p-5 xl:col-span-2"><b>Recent activity</b><div className="mt-4 space-y-3">{(o.audit||[]).slice(0,8).map(a=><div key={a.id} className="flex gap-3 border-b border-white/5 pb-3 text-sm"><Activity size={15} className="mt-0.5 text-vura-300"/><div><b>{a.actor_name||'System'}</b> · {a.action} {a.entity_type}<div className="text-xs text-white/35">{new Date(a.created_at).toLocaleString('en-NG')}</div></div></div>)}{!o.audit?.length&&<Empty text="No audit events yet."/>}</div></Card><Card className="p-5"><b>Operations</b><div className="mt-4 space-y-2"><Metric label="Notifications" value={notifications.length} onClick={()=>onTab('notifications')}/><Metric label="Order events" value={o.orderEvents?.length||0} onClick={()=>onTab('audit')}/><Metric label="Audit events" value={o.audit?.length||0} onClick={()=>onTab('audit')}/></div></Card></div></>}
function Payments({orders}:{orders:Order[]}){const pending=orders.filter(x=>x.payment_status==='pending_verification');const paid=orders.filter(x=>x.payment_status==='paid');return <><Header title="Payments" subtitle="Payment verification and paid-order visibility."/><div className="mt-6 grid gap-4 md:grid-cols-3"><Stat label="Pending verification" value={String(pending.length)}/><Stat label="Paid orders" value={String(paid.length)}/><Stat label="Paid volume" value={money(paid.reduce((n,x)=>n+Number(x.total_kobo),0))}/></div><Card className="mt-6 p-5"><b>Verification queue</b><div className="mt-4 space-y-2">{pending.map(x=><div key={x.id} className="flex justify-between border-b border-white/5 py-3"><span><b>{x.order_number}</b><small className="block text-white/35">{x.delivery_name}</small></span><b>{money(x.total_kobo)}</b></div>)}{!pending.length&&<Empty text="No payments awaiting verification."/>}</div></Card></>}
function Sourcing({orders}:{orders:Order[]}){const rows=orders.filter(x=>x.payment_status==='paid'&&!['delivered','cancelled'].includes(x.status));return <><Header title="Sourcing & delivery" subtitle="Paid orders awaiting purchasing, dispatch or delivery completion."/><Card className="mt-6 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr>{['Order','Customer','Product','Supplier','Status','Total'].map(x=><th key={x} className="border-b border-white/10 px-4 py-3 text-left text-xs text-white/35">{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-b border-white/5"><td className="px-4 py-3 font-bold">{x.order_number}</td><td className="px-4">{x.delivery_name}</td><td className="px-4">{x.product_name}</td><td className="px-4">{x.supplier_name||'Unassigned'}</td><td className="px-4"><Pill value={x.sourcing_status||x.status}/></td><td className="px-4 font-bold">{money(x.total_kobo)}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No sourcing work queued."/>}</Card></>}
function Customers({customers}:{customers:Customer[]}){return <><Header title="Customers" subtitle="Customer accounts and lifetime commercial value."/><Card className="mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr>{['Customer','Email','Orders','Lifetime spend'].map(x=><th key={x} className="border-b border-white/10 px-4 py-3 text-left text-xs text-white/35">{x}</th>)}</tr></thead><tbody>{customers.map(x=><tr key={x.id} className="border-b border-white/5"><td className="px-4 py-3 font-bold">{x.name}</td><td className="px-4">{x.email}</td><td className="px-4">{x.order_count}</td><td className="px-4 font-bold">{money(x.total_spend_kobo)}</td></tr>)}</tbody></table>{!customers.length&&<Empty text="No customers found."/>}</Card></>}
function Notifications({items}:{items:Notification[]}){return <><Header title="Notifications" subtitle="System and customer notification records."/><div className="mt-6 space-y-3">{items.map(x=><Card key={x.id} className="p-4"><div className="flex justify-between"><b>{x.title}</b><small className="text-white/30">{new Date(x.created_at).toLocaleString('en-NG')}</small></div><p className="mt-1 text-sm text-white/55">{x.body}</p><small className="text-white/30">{x.user_email||'System'}{x.order_number?` · ${x.order_number}`:''}</small></Card>)}{!items.length&&<Empty text="No notifications."/>}</div></>}
function AuditView({items,events}:{items:Audit[];events:OrderEvent[]}){return <><Header title="Audit log" subtitle="Immutable operational history for admin actions and order state changes."/><Card className="mt-6 p-5"><b>Admin changes</b><div className="mt-4 space-y-3">{items.map(x=><div key={x.id} className="border-b border-white/5 pb-3 text-sm"><b>{x.actor_name||'System'}</b> · {x.action} · {x.entity_type}{x.entity_id?` #${x.entity_id}`:''}<div className="text-xs text-white/35">{new Date(x.created_at).toLocaleString('en-NG')}</div></div>)}{!items.length&&<Empty text="No audit events."/>}</div></Card><Card className="mt-6 p-5"><b>Order events</b><div className="mt-4 space-y-3">{events.map(x=><div key={x.id} className="border-b border-white/5 pb-3 text-sm"><b>{x.actor_name||'System'}</b> · {x.event_type} · {x.order_number||x.order_id}<div className="text-xs text-white/35">{new Date(x.created_at).toLocaleString('en-NG')}</div></div>)}{!events.length&&<Empty text="No order events."/>}</div></Card></>}
function Header({title,subtitle}:{title:string;subtitle:string}){return <div><h1 className="text-3xl font-black tracking-tight">{title}</h1><p className="mt-2 text-sm text-white/45">{subtitle}</p></div>}
function Card({children,className=''}:{children:ReactNode;className?:string}){return <div className={`rounded-2xl border border-white/10 bg-white/[.025] ${className}`}>{children}</div>}
function Stat({label,value}:{label:string;value:string}){return <Card className="p-5"><div className="text-[11px] font-bold uppercase tracking-wider text-white/30">{label}</div><div className="mt-3 text-2xl font-black">{value}</div></Card>}
function Metric({label,value,onClick}:{label:string;value:number;onClick:()=>void}){return <button onClick={onClick} className="flex w-full justify-between rounded-xl border border-white/10 bg-white/[.02] p-3 text-left text-sm hover:bg-white/5"><span className="text-white/55">{label}</span><b>{value}</b></button>}
function Pill({value}:{value:string}){return <span className="rounded-full bg-white/5 px-2.5 py-1 text-[11px] font-bold capitalize">{String(value||'—').replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="py-12 text-center text-sm text-white/30"><Package className="mx-auto mb-2" size={26}/>{text}</div>}
function Loading(){return <div className="grid min-h-[50vh] place-items-center text-white/40"><RefreshCw className="animate-spin" size={18}/></div>}
