import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, Bot, Check, Clock, Loader2, Play, RefreshCw, Shield, ShieldAlert, X } from 'lucide-react';
import { authHeaders } from '@/lib/session';

type Job = { id:string; agent_id:string; task:string; status:string; attempts?:number; error?:string|null; provider?:string|null; model?:string|null; started_at?:string|null; completed_at?:string|null; result?:unknown; metadata?:unknown };
type Notif = { id:string; title:string; message:string; severity?:string; agent_id?:string; created_at?:string };
type Approval = { id:string; run_id?:string; agent_id?:string; tool_name?:string; risk?:string; input?:unknown; status?:string; requested_at?:string; decided_at?:string; decided_by?:string; decision_note?:string };
type Schedule = { id:string; agent_id?:string; task?:string; interval_minutes?:number; enabled?:boolean; last_enqueued_at?:string|null; next_run_at?:string|null };
type Mission = { id:string; goal:string; mission_type?:string; status:string; policy_level?:number; correlation_id?:string; opportunity_id?:string|null; created_at?:string; started_at?:string|null; completed_at?:string|null; error?:string|null };
type MissionStep = { id:string; mission_id?:string; step_key:string; agent_id?:string|null; depends_on?:string[]; status:string; run_id?:string|null; input?:unknown; result?:unknown; attempts?:number; max_attempts?:number; error?:string|null; sort_order?:number; started_at?:string|null; completed_at?:string|null };
type AgentEvent = { id:string; run_id?:string; event_type:string; tool_name?:string|null; risk?:string|null; input?:unknown; output?:unknown; error?:string|null; created_at?:string };

const AGENTS = [
  ['trend-intelligence','Trend','Find what is moving in the market. Fills Opportunities.','Scan Nigeria market demand and list evidence-backed opportunities'],
  ['product-intelligence','Product','Deep-dive one product idea (name in task).','Investigate MagSafe power bank for Nigeria retail'],
  ['marketing-intelligence','Marketing','Content angles and audience — no auto-posting.','Scout marketing angles for phone accessories in Nigeria'],
  ['sales','Sales','What sells, stock risk, follow-up ideas.','Sales and inventory intelligence scan'],
  ['operations','Operations','Orders and fulfillment health.','Operations fulfillment scan'],
  ['engineering','Engineering','Site and worker health check.','Engineering health and incident scan'],
] as const;
const TREND_CATEGORIES = ['phones','Phone Accessories','laptops','earphones','solar','inverters','Fashion','Shoes','Bags','Electronics','Gaming','Home Appliances','Beverages','Cars','Car Accessories'];
const MISSION_STATUS_COLOR: Record<string,string> = { queued:'text-amber-300',running:'text-sky-300',awaiting_approval:'text-violet-300',completed:'text-emerald-300',failed:'text-red-300',cancelled:'text-white/50' };
const STEP_STATUS_COLOR: Record<string,string> = { pending:'text-white/40',ready:'text-amber-300',queued:'text-amber-300',running:'text-sky-300',completed:'text-emerald-300',failed:'text-red-300',awaiting_approval:'text-violet-300',skipped:'text-white/40' };
function formatWhen(iso?:string|null){if(!iso)return '';const d=new Date(iso);if(Number.isNaN(d.getTime()))return '';const diff=Math.round((Date.now()-d.getTime())/1000);if(diff<60)return 'just now';if(diff<3600)return `${Math.floor(diff/60)}m ago`;if(diff<86400)return `${Math.floor(diff/3600)}h ago`;return d.toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}
function formatClock(iso?:string|null){if(!iso)return '—';const d=new Date(iso);return Number.isNaN(d.getTime())?'—':d.toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}
function statusColor(s:string){return s==='completed'?'text-emerald-300':s==='failed'?'text-red-300':s==='running'||s==='queued'?'text-amber-300':'text-white/50';}
function hasNestedMessage(v:unknown){if(typeof v==='string')return v;if(v&&typeof v==='object'){const o=v as Record<string,unknown>;if(typeof o.message==='string')return o.message;if(typeof o.note==='string')return o.note;return JSON.stringify(o);}return '';}

async function getApi<T>(resource:string):Promise<T>{const [res,...rest]=resource.split('&');let url=`/api/admin?resource=${encodeURIComponent(res)}`;if(rest.length)url+=`&${rest.join('&')}`;const r=await fetch(url,{credentials:'include',headers:authHeaders()});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error((b as {error?:string})?.error||`Failed (${r.status})`);return b as T;}
async function postAgent(body:Record<string,unknown>){const r=await fetch('/api/admin?resource=agents',{method:'POST',credentials:'include',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Start failed (${r.status})`);return b as {runId?:string;status?:string;message?:string};}
async function postMission(body:Record<string,unknown>){const r=await fetch('/api/admin?resource=agent-missions',{method:'POST',credentials:'include',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Start failed (${r.status})`);return b as {missionId?:string;correlationId?:string;status?:string};}
async function decideApproval(id:string,decision:'approved'|'rejected'){const r=await fetch('/api/admin?resource=agent-approvals',{method:'PATCH',credentials:'include',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({approvalId:id,decision})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Decision failed (${r.status})`);}

export default function StudioAgents(){
 const [jobs,setJobs]=useState<Job[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[opportunities,setOpportunities]=useState<unknown[]>([]),[notifications,setNotifications]=useState<Notif[]>([]),[missions,setMissions]=useState<Mission[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[banner,setBanner]=useState(''),[starting,setStarting]=useState<string|null>(null),[categories,setCategories]=useState<string[]>(['phones','Phone Accessories']);
 const [selectedJob,setSelectedJob]=useState<Job|null>(null),[selectedJobEvents,setSelectedJobEvents]=useState<AgentEvent[]>([]),[selectedNotif,setSelectedNotif]=useState<Notif|null>(null),[selectedMission,setSelectedMission]=useState<{mission:Mission;steps:MissionStep[]}|null>(null);
 const [missionGoal,setMissionGoal]=useState(''),[missionProduct,setMissionProduct]=useState(''),[startingMission,setStartingMission]=useState(false),[deciding,setDeciding]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [j,a,s,o,n,mi]=await Promise.all([getApi<{jobs:Job[]}>('agent-jobs&limit=50'),getApi<{approvals:Approval[]}>('agent-approvals&status=pending'),getApi<{schedules:Schedule[]}>('agent-schedules'),getApi<{opportunities:unknown[]}>('agent-opportunities&limit=20'),getApi<{notifications:Notif[]}>('agent-notifications&limit=30'),getApi<{missions:Mission[]}>('agent-missions')]);setJobs(j.jobs||[]);setApprovals(a.approvals||[]);setSchedules(s.schedules||[]);setOpportunities(o.opportunities||[]);setNotifications(n.notifications||[]);setMissions(mi.missions||[]);}catch(e){setError(e instanceof Error?e.message:'Failed to load command center')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const active=jobs.some(j=>j.status==='queued'||j.status==='running')||missions.some(m=>m.status==='running'||m.status==='queued');if(!active)return;const t=setInterval(()=>void load(),8000);return()=>clearInterval(t)},[jobs,missions,load]);
 const loadJob=useCallback(async(j:Job)=>{setSelectedJob(j);setSelectedJobEvents([]);try{const {events}=await getApi<{events:AgentEvent[]}>(`agent-events&runId=${encodeURIComponent(j.id)}`);setSelectedJobEvents(events||[])}catch{}},[]);
 const loadMission=useCallback(async(id:string)=>{try{setSelectedMission(await getApi<{mission:Mission;steps:MissionStep[]}>(`agent-missions&missionId=${encodeURIComponent(id)}`))}catch{setSelectedMission(null)}},[]);
 const running=jobs.filter(j=>j.status==='running'||j.status==='queued'),failed=jobs.filter(j=>j.status==='failed'),missionsInFlight=missions.filter(m=>m.status==='running'||m.status==='queued'||m.status==='awaiting_approval'),critical=notifications.filter(n=>n.severity==='critical');
 const deduped=useMemo(()=>{const seen=new Set<string>();return notifications.filter(n=>{const k=`${n.title}::${n.message}`;if(seen.has(k))return false;seen.add(k);return true})},[notifications]);
 const startAgent=async(agentId:string,task:string,extra?:Record<string,unknown>)=>{setStarting(agentId);setError('');try{const r=await postAgent({agentId,task,...extra});setBanner(r.runId?`Job started · ${r.status||'queued'} · ${r.runId.slice(0,8)}…`:r.message||'Job started.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not start agent')}finally{setStarting(null)}};
 const startMission=async()=>{if(missionGoal.trim().length<3)return;setStartingMission(true);setError('');try{const r=await postMission({goal:missionGoal.trim(),productName:missionProduct.trim()||undefined,categories});setBanner(`Growth mission started · ${r.status||'queued'}${r.correlationId?` · ${r.correlationId}`:''}`);setMissionGoal('');setMissionProduct('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not start mission')}finally{setStartingMission(false)}};
 const decide=async(a:Approval,d:'approved'|'rejected')=>{setDeciding(a.id);try{await decideApproval(a.id,d);setBanner(d==='approved'?'Approval granted.':'Approval rejected.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not record decision')}finally{setDeciding(null)}};
 const toggle=(c:string)=>setCategories(p=>p.includes(c)?p.filter(x=>x!==c):[...p,c]);
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-vura-300"><Bot size={18}/><span className="text-xs font-bold uppercase tracking-wider">Agents</span></div><h1 className="mt-1 text-2xl font-black text-white md:text-3xl">Command Center</h1><p className="mt-1 max-w-2xl text-sm text-white/45">Start a scan here. Agents research in the background, then fill <b className="text-white/70">Opportunities</b> and alerts. You stay in control of what gets listed.</p></div><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-bold text-white hover:bg-white/10"><RefreshCw size={16} className={loading?'animate-spin':''}/> Refresh</button></div>
  {error&&<p className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</p>}{banner&&<p className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{banner}</p>}
  <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Running / queued',running.length,running.length?'text-amber-300':'text-white'],['Failed (recent)',failed.length,failed.length?'text-red-300':'text-white'],['Pending approvals',approvals.length,approvals.length?'text-violet-300':'text-white'],['Missions in flight',missionsInFlight.length,missionsInFlight.length?'text-sky-300':'text-white'],['Opportunities',opportunities.length,'text-white'],['Critical alerts',critical.length,critical.length?'text-red-300':'text-white']].map(([label,n,color])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-white/35">{label==='Critical alerts'?<ShieldAlert size={11}/>:null}{label}</div><div className={`mt-1 text-2xl font-black ${color}`}>{n}</div></div>)}</section>
  <section className="rounded-2xl border border-vura-500/30 bg-gradient-to-br from-vura-500/10 to-transparent p-4 md:p-5"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div className="min-w-0 flex-1"><h2 className="text-sm font-black uppercase tracking-wider text-vura-200">Run market scan</h2><p className="mt-1 text-sm text-white/50">Pick categories you sell. Trend agent searches the web, scores ideas, and saves them under Opportunities.</p><div className="mt-3 flex flex-wrap gap-2">{TREND_CATEGORIES.map(c=>{const on=categories.includes(c);return <button key={c} type="button" onClick={()=>toggle(c)} className={`rounded-full border px-3 py-1.5 text-xs font-bold transition ${on?'border-vura-400/50 bg-vura-500/25 text-white':'border-white/10 bg-black/20 text-white/55 hover:border-white/25'}`}>{c}</button>})}</div></div><button type="button" disabled={!!starting||!categories.length} onClick={()=>void startAgent('trend-intelligence',`Scan Nigeria demand for: ${categories.join(', ')||'general retail'}`,{categories})} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-vura-500 px-5 py-3 text-sm font-black text-white shadow-lg shadow-vura-500/20 disabled:opacity-50">{starting==='trend-intelligence'?<Loader2 size={18} className="animate-spin"/>:<Play size={18}/>} Start Trend scan</button></div></section>
  <section className="rounded-2xl border border-vura-500/25 bg-gradient-to-br from-vura-500/[0.06] to-transparent p-4 md:p-5"><div className="flex items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-vura-200"><Activity size={14}/> Growth missions</h2>{missions.length>0&&<span className="text-[11px] text-white/40">{missions.filter(m=>m.status==='completed').length} completed · {missionsInFlight.length} in flight</span>}</div><p className="mt-1 text-sm text-white/45">Product → Marketing → Sales → Operations → <b className="text-vura-300">human approval gate</b>. Every step runs through the governed tool loop; nothing is published or written autonomously.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1.4fr]"><div className="rounded-xl border border-white/10 bg-black/20 p-4"><b className="text-xs text-white/80">Start a growth mission</b><input value={missionGoal} onChange={e=>setMissionGoal(e.target.value)} placeholder="Mission goal — e.g. Grow the solar power bank category" className="mt-3 w-full rounded-xl border border-white/10 bg-[#111522] px-3 py-2.5 text-sm outline-none focus:border-vura-500"/><input value={missionProduct} onChange={e=>setMissionProduct(e.target.value)} placeholder="Optional product to focus on" className="mt-2 w-full rounded-xl border border-white/10 bg-[#111522] px-3 py-2.5 text-sm outline-none focus:border-vura-500"/><button type="button" disabled={startingMission||missionGoal.trim().length<3} onClick={()=>void startMission()} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-vura-500 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{startingMission?<Loader2 size={16} className="animate-spin"/>:<Play size={16}/>} Start mission</button></div><div className="max-h-96 space-y-2 overflow-y-auto pr-1">{missions.length===0&&<p className="text-sm text-white/35">No missions yet — start one above.</p>}{missions.map(m=><button key={m.id} type="button" onClick={()=>void loadMission(m.id)} className="flex w-full flex-col rounded-xl border border-white/5 bg-black/20 px-3 py-2.5 text-left transition hover:border-vura-500/40 hover:bg-white/[0.04]"><div className="flex flex-wrap items-center gap-x-2 gap-y-0.5"><span className={`text-xs font-bold ${MISSION_STATUS_COLOR[m.status]||'text-white'}`}>{m.status}</span><span className="text-[10px] text-white/35">· policy L{m.policy_level??2}</span><span className="text-[10px] text-white/30">· {formatWhen(m.started_at||m.created_at)}</span><span className="ml-auto text-[10px] text-vura-300">Details →</span></div><span className="mt-1 block truncate text-sm text-white/85">{m.goal}</span>{m.error&&<span className="mt-0.5 block truncate text-xs text-red-300/90">{m.error}</span>}</button>)}</div></div></section>
  <section><div className="mb-2 flex items-center justify-between"><h2 className="text-xs font-bold uppercase tracking-wider text-white/40">Agent status</h2><span className="text-[10px] text-white/30">Tap an agent to view its latest run</span></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02]">{AGENTS.map(([id,label,blurb,task])=>{const last=jobs.find(j=>j.agent_id===id);return <div key={id} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-white/5 p-4 last:border-b-0"><button type="button" disabled={!last} onClick={()=>last&&void loadJob(last)} className="min-w-0 text-left disabled:cursor-default"><div className="flex items-center gap-2"><span className={`h-2 w-2 shrink-0 rounded-full ${last?.status==='failed'?'bg-red-400':last?.status==='running'?'bg-amber-300':'bg-emerald-300'}`}/><span className="text-sm font-bold text-white">{label}</span></div><p className="mt-1 truncate text-xs text-white/40">{blurb}</p><p className="mt-2 text-[11px] text-white/40">{last?<><span className={statusColor(last.status)}>{last.status}</span> · {formatWhen(last.completed_at||last.started_at)}</>:'No runs yet'}</p></button><button type="button" disabled={!!starting} onClick={()=>void startAgent(id,task,id==='trend-intelligence'?{categories}:undefined)} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-white hover:bg-white/10 disabled:opacity-50">{starting===id?<Loader2 size={14} className="animate-spin"/>:<Play size={14}/>} Run</button></div>})}</div></section>
  {loading&&jobs.length===0?<div className="flex justify-center py-12 text-white/40"><Loader2 className="animate-spin" size={28}/></div>:<>
  <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-white/40"><Clock size={14}/> Job history</h2><ul className="mt-3 max-h-80 space-y-2 overflow-y-auto">{jobs.length===0&&<li className="text-sm text-white/40">No jobs yet — start a Trend scan above.</li>}{jobs.slice(0,40).map(j=><li key={j.id}><button type="button" onClick={()=>void loadJob(j)} className="w-full rounded-xl border border-white/5 bg-black/20 px-3 py-2.5 text-left text-xs transition hover:border-vura-500/40 hover:bg-white/[0.04]"><div className="flex flex-wrap items-center gap-x-2"><span className="font-bold text-white/85">{j.agent_id}</span><span className={statusColor(j.status)}>{j.status}</span><span className="text-white/30">·</span><span className="text-white/40">{formatWhen(j.completed_at||j.started_at)||'—'}</span><span className="ml-auto text-[10px] text-vura-300">View →</span></div><span className="mt-0.5 block truncate text-white/50">{j.task}</span>{j.error&&<span className="mt-0.5 block truncate text-red-300/90">{j.error}</span>}</button></li>)}</ul></section>
  <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-white/40"><Shield size={14}/> Approval requests</h2><p className="mt-1 text-xs text-white/40">An agent proposes a write or destructive action here. Nothing executes until you approve.</p>{approvals.length===0?<p className="mt-3 text-sm text-white/40">No pending approvals.</p>:<ul className="mt-3 space-y-2">{approvals.map(a=><li key={a.id} className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="flex flex-wrap items-center gap-x-2 text-xs"><span className={`font-bold ${a.risk==='destructive'?'text-red-300':'text-violet-300'}`}>{a.risk}</span><span className="font-bold text-white/85">{a.tool_name}</span><span className="text-white/35">· {a.agent_id||'agent'}</span></div><p className="mt-1 text-xs text-white/55">{hasNestedMessage(a.input)||'Review requested action.'}</p><div className="mt-2 flex gap-2"><button type="button" disabled={deciding===a.id} onClick={()=>void decide(a,'approved')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-500/90 px-3 py-1.5 text-xs font-bold text-black disabled:opacity-50"><Check size={12}/> Approve</button><button type="button" disabled={deciding===a.id} onClick={()=>void decide(a,'rejected')} className="inline-flex items-center gap-1 rounded-lg border border-red-400/30 bg-red-500/10 px-3 py-1.5 text-xs font-bold text-red-300 disabled:opacity-50"><X size={12}/> Reject</button></div></li>)}</ul>}</section>
  <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h2 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-white/40"><Clock size={14}/> Schedules</h2>{schedules.length===0?<p className="mt-2 text-sm text-white/40">No schedules configured.</p>:<ul className="mt-3 space-y-2 text-xs">{schedules.map(s=><li key={s.id} className="flex flex-wrap items-center gap-x-2 rounded-lg border border-white/5 bg-black/15 px-3 py-2"><span className="font-bold text-white/85">{s.agent_id||'agent'}</span><span className="text-white/45">every {s.interval_minutes}m</span><span className={s.enabled?'text-emerald-300':'text-white/35'}>{s.enabled?'enabled':'disabled'}</span><span className="text-white/30">· next {formatClock(s.next_run_at)}</span></li>)}</ul>}</section>
  <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-white/40">Alerts & history</h2><ul className="mt-3 space-y-2">{deduped.length===0&&<li className="text-sm text-white/40">No alerts yet.</li>}{deduped.slice(0,15).map(n=><li key={n.id}><button type="button" onClick={()=>setSelectedNotif(n)} className="w-full rounded-xl border border-white/5 bg-black/15 px-3 py-2 text-left transition hover:border-vura-500/40"><div className="flex items-baseline justify-between gap-2"><b className="text-sm text-white/85">{n.title}</b><span className="text-[11px] text-white/35">{formatWhen(n.created_at)}</span></div><span className="mt-0.5 block line-clamp-2 text-xs text-white/45">{n.message}</span></button></li>)}</ul></section></>}
  {selectedJob&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 p-3 sm:items-center" onClick={()=>setSelectedJob(null)}><div className="max-h-[88vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#12151f] p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-white/40">Agent run</p><h3 className="mt-1 text-xl font-black text-white">{selectedJob.agent_id}</h3></div><button type="button" onClick={()=>setSelectedJob(null)} className="rounded-lg px-2 py-1 text-sm text-white/60 hover:bg-white/5">Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-[10px] uppercase text-white/35">Status</p><p className={statusColor(selectedJob.status)}>{selectedJob.status}</p></div><div><p className="text-[10px] uppercase text-white/35">When</p><p className="text-sm text-white/70">{formatWhen(selectedJob.completed_at||selectedJob.started_at)||'—'}</p></div></div><div className="mt-4"><p className="text-[10px] font-bold uppercase text-white/35">Task</p><p className="mt-1 text-sm text-white/80">{selectedJob.task}</p></div>{selectedJob.error&&<div className="mt-4 border-l-2 border-red-400 bg-red-400/10 p-3 text-sm text-red-200">{selectedJob.error}</div>}<div className="mt-5"><p className="text-[10px] font-bold uppercase text-white/35">What the agent returned</p>{selectedJob.result!=null?<pre className="mt-2 max-h-72 overflow-auto rounded-xl border border-white/10 bg-black/50 p-4 text-xs leading-5 text-white/75 whitespace-pre-wrap">{typeof selectedJob.result==='string'?selectedJob.result:JSON.stringify(selectedJob.result,null,2)}</pre>:<p className="mt-2 text-sm text-white/40">No result payload was returned for this run.</p>}</div>{selectedJobEvents.length>0&&<div className="mt-5"><p className="text-[10px] font-bold uppercase text-white/35">Tool activity</p><ul className="mt-2 space-y-1.5">{selectedJobEvents.map(ev=><li key={ev.id} className="rounded-lg border border-white/5 bg-black/25 px-3 py-2 text-[11px]"><div className="flex flex-wrap items-center gap-x-2"><span className={ev.event_type==='tool.failed'?'text-red-300':ev.risk==='write'||ev.risk==='destructive'?'text-violet-300':'text-sky-300'}>{ev.event_type}</span>{ev.tool_name&&<span className="font-mono text-white/80">{ev.tool_name}</span>}<span className="ml-auto text-white/35">{formatWhen(ev.created_at)}</span></div>{ev.error&&<p className="mt-1 text-red-300">{ev.error}</p>}</li>)}</ul></div>}</div></div>}
  {selectedMission&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 p-3 sm:items-center" onClick={()=>setSelectedMission(null)}><div className="max-h-[88vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#12151f] p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-wider text-white/40">Growth mission</p><h3 className="mt-1 text-xl font-black text-white">{selectedMission.mission.goal}</h3></div><button type="button" onClick={()=>setSelectedMission(null)} className="text-sm text-white/60">Close</button></div><div className="mt-4 space-y-2">{selectedMission.steps.map(st=><div key={st.id} className="rounded-xl border border-white/5 bg-black/25 p-3"><div className="flex flex-wrap gap-2 text-xs"><span className={STEP_STATUS_COLOR[st.status]||'text-white'}>{st.status}</span><b className="text-white/85">{st.step_key}</b><span className="text-white/40">· {st.agent_id||'human gate'}</span></div>{st.error&&<p className="mt-1 text-xs text-red-300">{st.error}</p>}</div>)}</div></div></div>}
  {selectedNotif&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/70 p-3 sm:items-center" onClick={()=>setSelectedNotif(null)}><div className="max-h-[88vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-white/10 bg-[#12151f] p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between gap-2"><h3 className="text-lg font-black text-white">{selectedNotif.title}</h3><button type="button" onClick={()=>setSelectedNotif(null)} className="text-sm text-white/60">Close</button></div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-white/75">{selectedNotif.message}</p></div></div>}
 </div>;
}
