import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, Bot, Check, ChevronRight, Clock, Loader2, Play, RefreshCw, Shield, ShieldAlert, X } from 'lucide-react';
import { authHeaders } from '@/lib/session';

type Job = { id:string; agent_id:string; task:string; status:string; attempts?:number; error?:string|null; provider?:string|null; model?:string|null; started_at?:string|null; completed_at?:string|null; result?:unknown; metadata?:unknown };
type Notif = { id:string; title:string; message:string; severity?:string; agent_id?:string; created_at?:string };
type Approval = { id:string; run_id?:string; agent_id?:string; tool_name?:string; risk?:string; input?:unknown; status?:string; requested_at?:string; decided_at?:string; decided_by?:string; decision_note?:string };
type Schedule = { id:string; agent_id?:string; task?:string; interval_minutes?:number; enabled?:boolean; last_enqueued_at?:string|null; next_run_at?:string|null };
type Mission = { id:string; goal:string; mission_type?:string; status:string; policy_level?:number; correlation_id?:string; opportunity_id?:string|null; created_at?:string; started_at?:string|null; completed_at?:string|null; error?:string|null };
type MissionStep = { id:string; mission_id?:string; step_key:string; agent_id?:string|null; depends_on?:string[]; status:string; run_id?:string|null; input?:unknown; result?:unknown; attempts?:number; max_attempts?:number; error?:string|null; sort_order?:number; started_at?:string|null; completed_at?:string|null };
type AgentEvent = { id:string; run_id?:string; event_type:string; tool_name?:string|null; risk?:string|null; input?:unknown; output?:unknown; error?:string|null; created_at?:string };

const AGENTS = [
  ['trend-intelligence','Trend','Find what is moving in the market. Fills Opportunities.','Scan Nigeria market demand and list evidence-backed opportunities'],
  ['product-intelligence','Product','Deep-dive one product idea.','Investigate MagSafe power bank for Nigeria retail'],
  ['marketing-intelligence','Marketing','Content angles and audience. No auto-posting.','Scout marketing angles for phone accessories in Nigeria'],
  ['sales','Sales','What sells, stock risk and follow-up ideas.','Sales and inventory intelligence scan'],
  ['operations','Operations','Orders and fulfillment health.','Operations fulfillment scan'],
  ['engineering','Engineering','Site and worker health check.','Engineering health and incident scan'],
] as const;
const TREND_CATEGORIES = ['phones','Phone Accessories','laptops','earphones','solar','inverters','Fashion','Shoes','Bags','Electronics','Gaming','Home Appliances','Beverages','Cars','Car Accessories'];
const MISSION_STATUS_COLOR: Record<string,string> = { queued:'text-amber-300',running:'text-sky-300',awaiting_approval:'text-violet-300',completed:'text-emerald-300',failed:'text-red-300',cancelled:'text-white/50' };
const STEP_STATUS_COLOR: Record<string,string> = { pending:'text-white/40',ready:'text-amber-300',queued:'text-amber-300',running:'text-sky-300',completed:'text-emerald-300',failed:'text-red-300',awaiting_approval:'text-violet-300',skipped:'text-white/40' };

function formatWhen(iso?:string|null){ if(!iso)return ''; const d=new Date(iso); if(Number.isNaN(d.getTime()))return ''; const diff=Math.round((Date.now()-d.getTime())/1000); if(diff<60)return 'just now'; if(diff<3600)return `${Math.floor(diff/60)}m ago`; if(diff<86400)return `${Math.floor(diff/3600)}h ago`; return d.toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}); }
function formatClock(iso?:string|null){ if(!iso)return '—'; const d=new Date(iso); return Number.isNaN(d.getTime())?'—':d.toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}); }
function statusColor(s:string){ return s==='completed'?'text-emerald-300':s==='failed'?'text-red-300':s==='running'||s==='queued'?'text-amber-300':'text-white/50'; }
function labelize(value:string){ return value.replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase()); }
function asRecord(v:unknown):Record<string,unknown>|null{ return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:null; }
function asArray(v:unknown):unknown[]{ return Array.isArray(v)?v:[]; }
function textValue(v:unknown){ return typeof v==='string'?v:''; }

function getHumanResult(job:Job){
 const r=asRecord(job.result);
 if(!r)return {headline:job.status==='completed'?'The agent completed its work.':'The agent did not return a readable result.',summary:'Open technical details only if you need the underlying system output.',metrics:[] as {label:string;value:string}[],items:[] as string[],actions:[] as string[]};
 const summary=asRecord(r.summary);
 const metrics:{label:string;value:string}[]=[];
 if(summary) Object.entries(summary).slice(0,8).forEach(([k,v])=>{ if(typeof v==='number'||typeof v==='string')metrics.push({label:labelize(k),value:String(v)}); });
 const alerts=asArray(r.alerts).map(textValue).filter(Boolean);
 const actions=asArray(r.recommended_actions).map(textValue).filter(Boolean);
 const items=[...asArray(r.items),...asArray(r.opportunities),...asArray(r.findings)].map(v=>{const o=asRecord(v); if(o)return textValue(o.title)||textValue(o.name)||textValue(o.summary)||textValue(o.recommendation)||textValue(o.message); return textValue(v)}).filter(Boolean).slice(0,8);
 const headline=textValue(r.headline)||textValue(r.summary_text)||textValue(r.overview)||alerts[0]||items[0]||(job.status==='completed'?'The agent completed its work.':'The agent is still processing.');
 const summaryText=textValue(r.explanation)||textValue(r.reason)||textValue(r.description)||textValue(r.note)||'';
 return {headline,summary:summaryText,metrics,items,actions:[...actions,...alerts].slice(0,6)};
}

async function getApi<T>(resource:string):Promise<T>{ const [res,...rest]=resource.split('&'); let url=`/api/admin?resource=${encodeURIComponent(res)}`; if(rest.length)url+=`&${rest.join('&')}`; const r=await fetch(url,{credentials:'include',headers:authHeaders()}); const b=await r.json().catch(()=>({})); if(!r.ok)throw new Error((b as {error?:string})?.error||`Failed (${r.status})`); return b as T; }
async function postAgent(body:Record<string,unknown>){ const r=await fetch('/api/admin?resource=agents',{method:'POST',credentials:'include',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)}); const b=await r.json().catch(()=>({})); if(!r.ok)throw new Error(b.error||`Start failed (${r.status})`); return b as {runId?:string;status?:string;message?:string}; }
async function postMission(body:Record<string,unknown>){ const r=await fetch('/api/admin?resource=agent-missions',{method:'POST',credentials:'include',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)}); const b=await r.json().catch(()=>({})); if(!r.ok)throw new Error(b.error||`Start failed (${r.status})`); return b as {missionId?:string;correlationId?:string;status?:string}; }
async function decideApproval(id:string,decision:'approved'|'rejected'){ const r=await fetch('/api/admin?resource=agent-approvals',{method:'PATCH',credentials:'include',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({approvalId:id,decision})}); const b=await r.json().catch(()=>({})); if(!r.ok)throw new Error(b.error||`Decision failed (${r.status})`); }

function ResultView({job}:{job:Job}){
 const human=getHumanResult(job);
 return <div className="space-y-5">
  <div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">What you need to know</div><h3 className="mt-2 text-xl font-bold text-white">{human.headline}</h3>{human.summary&&<p className="mt-2 text-sm leading-6 text-white/55">{human.summary}</p>}</div>
  {human.metrics.length>0&&<div className="grid grid-cols-2 gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-4">{human.metrics.map(m=><div key={m.label} className="bg-[#0d0f16] px-4 py-3"><div className="text-[10px] font-bold uppercase tracking-wider text-white/35">{m.label}</div><div className="mt-1 text-lg font-bold text-white">{m.value}</div></div>)}</div>}
  {human.actions.length>0&&<div><div className="mb-2 text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Attention / recommended action</div><div className="space-y-2">{human.actions.map((x,i)=><div key={`${x}-${i}`} className="border-l-2 border-amber-400/60 bg-amber-400/[0.06] px-4 py-3 text-sm text-white/75">{x}</div>)}</div></div>}
  {human.items.length>0&&<div><div className="mb-2 text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Key findings</div><div className="divide-y divide-white/10 border-y border-white/10">{human.items.map((x,i)=><div key={`${x}-${i}`} className="flex gap-3 py-3 text-sm text-white/70"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-vura-400"/>{x}</div>)}</div></div>}
  <details className="border-t border-white/10 pt-4"><summary className="cursor-pointer text-xs font-bold text-white/35 hover:text-white/60">Technical details</summary><pre className="mt-3 max-h-80 overflow-auto rounded-lg bg-black/50 p-4 text-xs leading-5 text-white/45">{JSON.stringify(job.result,null,2)}</pre></details>
 </div>;
}

export default function StudioAgents(){
 const [jobs,setJobs]=useState<Job[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[opportunities,setOpportunities]=useState<unknown[]>([]),[notifications,setNotifications]=useState<Notif[]>([]),[missions,setMissions]=useState<Mission[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[banner,setBanner]=useState(''),[starting,setStarting]=useState<string|null>(null),[categories,setCategories]=useState<string[]>(['phones','Phone Accessories']);
 const [selectedJob,setSelectedJob]=useState<Job|null>(null),[selectedJobEvents,setSelectedJobEvents]=useState<AgentEvent[]>([]),[selectedNotif,setSelectedNotif]=useState<Notif|null>(null),[selectedMission,setSelectedMission]=useState<{mission:Mission;steps:MissionStep[]}|null>(null);
 const [missionGoal,setMissionGoal]=useState(''),[missionProduct,setMissionProduct]=useState(''),[startingMission,setStartingMission]=useState(false),[deciding,setDeciding]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [j,a,s,o,n,mi]=await Promise.all([getApi<{jobs:Job[]}>('agent-jobs&limit=50'),getApi<{approvals:Approval[]}>('agent-approvals&status=pending'),getApi<{schedules:Schedule[]}>('agent-schedules'),getApi<{opportunities:unknown[]}>('agent-opportunities&limit=20'),getApi<{notifications:Notif[]}>('agent-notifications&limit=30'),getApi<{missions:Mission[]}>('agent-missions')]);setJobs(j.jobs||[]);setApprovals(a.approvals||[]);setSchedules(s.schedules||[]);setOpportunities(o.opportunities||[]);setNotifications(n.notifications||[]);setMissions(mi.missions||[]);}catch(e){setError(e instanceof Error?e.message:'Failed to load command center')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const active=jobs.some(j=>j.status==='queued'||j.status==='running')||missions.some(m=>m.status==='running'||m.status==='queued');if(!active)return;const t=setInterval(()=>void load(),8000);return()=>clearInterval(t)},[jobs,missions,load]);
 const loadJob=useCallback(async(j:Job)=>{setSelectedJob(j);setSelectedJobEvents([]);try{const {events}=await getApi<{events:AgentEvent[]}>(`agent-events&runId=${encodeURIComponent(j.id)}`);setSelectedJobEvents(events||[])}catch{}},[]);
 const loadMission=useCallback(async(id:string)=>{try{setSelectedMission(await getApi<{mission:Mission;steps:MissionStep[]}>(`agent-missions&missionId=${encodeURIComponent(id)}`))}catch{setSelectedMission(null)}},[]);
 const running=jobs.filter(j=>j.status==='running'||j.status==='queued'),failed=jobs.filter(j=>j.status==='failed'),missionsInFlight=missions.filter(m=>m.status==='running'||m.status==='queued'||m.status==='awaiting_approval'),critical=notifications.filter(n=>n.severity==='critical');
 const deduped=useMemo(()=>{const seen=new Set<string>();return notifications.filter(n=>{const k=`${n.title}::${n.message}`;if(seen.has(k))return false;seen.add(k);return true})},[notifications]);
 const startAgent=async(agentId:string,task:string,extra?:Record<string,unknown>)=>{setStarting(agentId);setError('');try{const r=await postAgent({agentId,task,...extra});setBanner(r.runId?`Job started · ${r.status||'queued'}`:r.message||'Job started.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not start agent')}finally{setStarting(null)}};
 const startMission=async()=>{if(missionGoal.trim().length<3)return;setStartingMission(true);setError('');try{const r=await postMission({goal:missionGoal.trim(),productName:missionProduct.trim()||undefined,categories});setBanner(`Growth mission started · ${r.status||'queued'}`);setMissionGoal('');setMissionProduct('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not start mission')}finally{setStartingMission(false)}};
 const decide=async(a:Approval,d:'approved'|'rejected')=>{setDeciding(a.id);try{await decideApproval(a.id,d);setBanner(d==='approved'?'Approval granted.':'Approval rejected.');await load()}catch(e){setError(e instanceof Error?e.message:'Could not record decision')}finally{setDeciding(null)}};
 const toggle=(c:string)=>setCategories(p=>p.includes(c)?p.filter(x=>x!==c):[...p,c]);
 return <div className="space-y-6">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-vura-300"><Bot size={18}/><span className="text-xs font-bold uppercase tracking-wider">Agents</span></div><h1 className="mt-1 text-2xl font-black text-white md:text-3xl">Command Center</h1><p className="mt-1 max-w-2xl text-sm text-white/45">Agents research in the background and turn their findings into clear business decisions. Technical output stays hidden unless you need it.</p></div><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-4 py-2.5 text-sm font-bold text-white hover:bg-white/[0.07]"><RefreshCw size={16} className={loading?'animate-spin':''}/> Refresh</button></div>
  {error&&<p className="border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</p>}{banner&&<p className="border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{banner}</p>}
  <section className="grid grid-cols-2 border border-white/10 bg-white/[0.02] sm:grid-cols-3 lg:grid-cols-6">{[['Running',running.length,running.length?'text-amber-300':'text-white'],['Failed',failed.length,failed.length?'text-red-300':'text-white'],['Approvals',approvals.length,approvals.length?'text-violet-300':'text-white'],['Missions',missionsInFlight.length,missionsInFlight.length?'text-sky-300':'text-white'],['Opportunities',opportunities.length,'text-white'],['Alerts',critical.length,critical.length?'text-red-300':'text-white']].map(([label,n,color])=><div key={String(label)} className="border-r border-b border-white/10 px-4 py-3 last:border-r-0"><div className="text-[10px] font-bold uppercase tracking-wider text-white/35">{label}</div><div className={`mt-1 text-xl font-bold ${color}`}>{n}</div></div>)}</section>
  <section className="border border-white/10 bg-[#0b0d13]"><div className="border-b border-white/10 p-4 md:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-vura-300">Market intelligence</div><h2 className="mt-1 text-lg font-bold text-white">Run a market scan</h2><p className="mt-1 text-sm text-white/45">Choose the categories Vura sells. The Trend agent researches demand and creates opportunities for review.</p></div><button type="button" disabled={!!starting||!categories.length} onClick={()=>void startAgent('trend-intelligence',`Scan Nigeria demand for: ${categories.join(', ')||'general retail'}`,{categories})} className="inline-flex items-center justify-center gap-2 bg-vura-500 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{starting==='trend-intelligence'?<Loader2 size={17} className="animate-spin"/>:<Play size={17}/>} Run scan</button></div></div><div className="flex flex-wrap gap-2 p-4 md:p-5">{TREND_CATEGORIES.map(c=>{const on=categories.includes(c);return <button key={c} type="button" onClick={()=>toggle(c)} className={`border px-3 py-2 text-xs font-bold transition ${on?'border-vura-400/70 bg-vura-500/10 text-white':'border-white/10 text-white/45 hover:border-white/25 hover:text-white/70'}`}>{c}</button>})}</div></section>
  <section className="border border-white/10 bg-[#0b0d13]"><div className="border-b border-white/10 p-4 md:p-5"><div className="flex items-center justify-between gap-3"><div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-vura-300">Workflow</div><h2 className="mt-1 text-lg font-bold text-white">Growth missions</h2></div><span className="text-xs text-white/35">{missions.filter(m=>m.status==='completed').length} completed · {missionsInFlight.length} active</span></div><p className="mt-2 text-sm text-white/45">Product → Marketing → Sales → Operations → human approval. Controlled actions remain gated.</p></div><div className="grid gap-5 p-4 md:grid-cols-[1fr_1.2fr] md:p-5"><div><div className="text-sm font-bold text-white/80">Start a mission</div><input value={missionGoal} onChange={e=>setMissionGoal(e.target.value)} placeholder="Mission goal" className="mt-3 w-full border border-white/10 bg-[#10131b] px-3 py-3 text-sm outline-none focus:border-vura-500"/><input value={missionProduct} onChange={e=>setMissionProduct(e.target.value)} placeholder="Optional product" className="mt-2 w-full border border-white/10 bg-[#10131b] px-3 py-3 text-sm outline-none focus:border-vura-500"/><button type="button" disabled={startingMission||missionGoal.trim().length<3} onClick={()=>void startMission()} className="mt-2 inline-flex w-full items-center justify-center gap-2 bg-vura-500 px-4 py-3 text-sm font-bold text-white disabled:opacity-40">{startingMission?<Loader2 size={16} className="animate-spin"/>:<Play size={16}/>} Start mission</button></div><div className="border-l border-white/10 pl-0 md:pl-5">{missions.length===0?<div className="py-8 text-sm text-white/35">No missions yet.</div>:<div className="divide-y divide-white/10">{missions.slice(0,8).map(m=><button key={m.id} type="button" onClick={()=>void loadMission(m.id)} className="flex w-full items-center justify-between gap-4 py-3 text-left hover:bg-white/[0.02]"><div className="min-w-0"><div className="truncate text-sm font-semibold text-white/80">{m.goal}</div><div className="mt-1 text-xs text-white/30">{formatWhen(m.created_at)}</div></div><div className="flex items-center gap-2"><span className={`text-[10px] font-bold uppercase ${MISSION_STATUS_COLOR[m.status]||'text-white/40'}`}>{labelize(m.status)}</span><ChevronRight size={15} className="text-white/25"/></div></button>)}</div>}</div></div></section>
  <section className="border border-white/10 bg-[#0b0d13]"><div className="border-b border-white/10 p-4"><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Agent status</div><p className="mt-1 text-sm text-white/40">Tap an agent to inspect its latest business briefing. Use Run only when you want a new scan.</p></div><div className="divide-y divide-white/10">{AGENTS.map(([id,name,desc,task])=>{const latest=jobs.find(j=>j.agent_id===id);const active=latest?.status==='running'||latest?.status==='queued';return <div key={id} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><button type="button" onClick={()=>latest&&void loadJob(latest)} disabled={!latest} className="min-w-0 flex-1 text-left disabled:cursor-default"><div className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${active?'bg-amber-300':latest?.status==='failed'?'bg-red-400':'bg-emerald-300'}`}/><div className="min-w-0"><div className="text-sm font-bold text-white">{name}</div><div className="mt-0.5 truncate text-sm text-white/40">{desc}</div><div className="mt-1 text-xs text-white/25">{latest?`${labelize(latest.status)} · ${formatWhen(latest.completed_at||latest.started_at)}`:'No run yet'}{latest?' · tap to view briefing':''}</div></div></div></button><button type="button" disabled={!!starting} onClick={()=>void startAgent(id,task)} className="inline-flex shrink-0 items-center justify-center gap-2 border border-white/10 px-4 py-2 text-sm font-bold text-white/75 hover:border-white/25 hover:text-white disabled:opacity-40">{starting===id?<Loader2 size={15} className="animate-spin"/>:<Play size={15}/>} Run</button></div>})}</div></section>
  <section className="border border-white/10 bg-[#0b0d13]"><div className="border-b border-white/10 p-4"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-white/35"><Shield size={14}/> Approval queue</div><p className="mt-1 text-sm text-white/40">Controlled writes require explicit approval and remain in the audit trail.</p></div>{approvals.length===0?<div className="p-5 text-sm text-white/35">No pending approvals.</div>:<div className="divide-y divide-white/10">{approvals.map(a=><div key={a.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-white/80">{labelize(a.agent_id||'agent')} wants approval</div><div className="mt-1 text-xs text-white/35">{a.tool_name||'Controlled action'} · {formatWhen(a.requested_at)}</div></div><div className="flex gap-2"><button type="button" disabled={deciding===a.id} onClick={()=>void decide(a,'rejected')} className="border border-white/10 px-3 py-2 text-xs font-bold text-white/55">Reject</button><button type="button" disabled={deciding===a.id} onClick={()=>void decide(a,'approved')} className="bg-vura-500 px-3 py-2 text-xs font-bold text-white">Approve</button></div></div>)}</div>}</section>
  <section className="border border-white/10 bg-[#0b0d13]"><div className="border-b border-white/10 p-4 text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Schedules</div><div className="divide-y divide-white/10">{schedules.map(s=><div key={s.id} className="grid grid-cols-[1fr_auto] gap-3 px-4 py-3 text-sm sm:grid-cols-[1fr_1fr_1fr]"><div className="font-semibold text-white/70">{labelize(s.agent_id||'agent')}</div><div className="text-white/35">every {s.interval_minutes||'—'}m · {s.enabled?'enabled':'disabled'}</div><div className="text-white/30 sm:text-right">{formatClock(s.next_run_at)}</div></div>)}</div></section>
  <section className="border border-white/10 bg-[#0b0d13]"><div className="border-b border-white/10 p-4 text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Alerts & history</div><div className="divide-y divide-white/10">{deduped.slice(0,20).map(n=><button key={n.id} type="button" onClick={()=>setSelectedNotif(n)} className="flex w-full items-start justify-between gap-4 px-4 py-4 text-left hover:bg-white/[0.02]"><div className="min-w-0"><div className="text-sm font-semibold text-white/75">{n.title}</div><div className="mt-1 truncate text-sm text-white/35">{n.message}</div></div><span className="shrink-0 text-xs text-white/25">{formatWhen(n.created_at)}</span></button>)}{deduped.length===0&&<div className="p-5 text-sm text-white/35">No alerts or history yet.</div>}</div></section>
  {selectedJob&&<div className="fixed inset-0 z-50 bg-black/70 p-3 backdrop-blur-sm md:p-6" onClick={()=>setSelectedJob(null)}><div className="mx-auto flex h-full max-w-3xl items-center justify-center" onClick={e=>e.stopPropagation()}><div className="max-h-[90vh] w-full overflow-auto border border-white/10 bg-[#0d1018] shadow-2xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-white/10 bg-[#0d1018] p-5"><div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Agent briefing</div><h2 className="mt-1 text-2xl font-bold text-white">{labelize(selectedJob.agent_id)}</h2><div className={`mt-1 text-sm font-semibold ${statusColor(selectedJob.status)}`}>{labelize(selectedJob.status)} · {formatWhen(selectedJob.completed_at||selectedJob.started_at)}</div></div><button type="button" onClick={()=>setSelectedJob(null)} className="p-2 text-white/45 hover:text-white"><X size={20}/></button></div><div className="p-5"><div className="mb-5 grid gap-3 border-b border-white/10 pb-5 sm:grid-cols-3"><div><div className="text-[10px] font-bold uppercase text-white/30">Task</div><div className="mt-1 text-sm text-white/70">{selectedJob.task}</div></div><div><div className="text-[10px] font-bold uppercase text-white/30">Started</div><div className="mt-1 text-sm text-white/60">{formatClock(selectedJob.started_at)}</div></div><div><div className="text-[10px] font-bold uppercase text-white/30">Completed</div><div className="mt-1 text-sm text-white/60">{formatClock(selectedJob.completed_at)}</div></div></div><ResultView job={selectedJob}/><details className="mt-6 border-t border-white/10 pt-4"><summary className="cursor-pointer text-xs font-bold text-white/35">Agent activity</summary><div className="mt-3 divide-y divide-white/10">{selectedJobEvents.map(e=><div key={e.id} className="py-3 text-xs text-white/40"><div className="flex justify-between gap-3"><span>{labelize(e.event_type)}</span><span>{formatWhen(e.created_at)}</span></div>{e.tool_name&&<div className="mt-1">Tool: {e.tool_name}</div>}</div>)}{selectedJobEvents.length===0&&<div className="py-3 text-white/30">No activity recorded.</div>}</div></details></div></div></div></div>}
  {selectedNotif&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={()=>setSelectedNotif(null)}><div className="w-full max-w-lg border border-white/10 bg-[#0d1018] p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Alert</div><h2 className="mt-1 text-xl font-bold text-white">{selectedNotif.title}</h2></div><button onClick={()=>setSelectedNotif(null)} className="text-white/45"><X/></button></div><p className="mt-5 text-sm leading-6 text-white/65">{selectedNotif.message}</p></div></div>}
  {selectedMission&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={()=>setSelectedMission(null)}><div className="max-h-[85vh] w-full max-w-2xl overflow-auto border border-white/10 bg-[#0d1018] p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/35">Mission</div><h2 className="mt-1 text-xl font-bold text-white">{selectedMission.mission.goal}</h2><div className={`mt-1 text-xs font-bold uppercase ${MISSION_STATUS_COLOR[selectedMission.mission.status]||'text-white/40'}`}>{labelize(selectedMission.mission.status)}</div></div><button onClick={()=>setSelectedMission(null)} className="text-white/45"><X/></button></div><div className="mt-5 divide-y divide-white/10 border-y border-white/10">{selectedMission.steps.map((s,i)=><div key={s.id} className="flex items-center gap-4 py-4"><div className="flex h-7 w-7 items-center justify-center border border-white/10 text-xs text-white/45">{i+1}</div><div className="min-w-0 flex-1"><div className="text-sm font-semibold text-white/75">{labelize(s.step_key)}</div><div className={`mt-1 text-[10px] font-bold uppercase ${STEP_STATUS_COLOR[s.status]||'text-white/40'}`}>{labelize(s.status)}</div></div><Check size={16} className={s.status==='completed'?'text-emerald-300':'text-white/15'}/></div>)}</div></div></div>}
 </div>;
}
